server:
  port: 8088
spring:
  application:
    name: jmalcloud
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  http:
    encoding:
      force: true
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=100,maximumSize=500,expireAfterWrite=3600s
